name: Horizon
version: '1.0.0'
main: cz.goldzone.horizon.Main
api-version: '1.21'

commands:
  horizon:
    description: Main command for Horizon plugin
    aliases:
      - pw
      - pwarp
  warp:
    description: Teleports to warp
  warps:
    description: List of warps
  setwarp:
    description: Set warp
  delwarp:
    description: Delete warp
  sethome:
    description: Set home
  delhome:
    description: Delete home
  home:
    description: Teleports to home
  homes:
    description: List of homes
