name: Horizon
author: MrJogger_
version: '1.0.1'
main: cz.goldzone.horizon.Main
api-version: '1.21'

commands:
  horizon:
    description: Main command for Horizon plugin
  warp:
    description: Teleports to warp
  warps:
    description: List of warps
  setwarp:
    description: Set a warp
  delwarp:
    description: Delete a warp
  sethome:
    description: Set home location
  delhome:
    description: Delete home location
  home:
    description: Teleports to home
  homes:
    description: List of homes
  wb:
    description: Opens a crafting table
  enderchest:
    description: Opens an ender chest
    aliases:
      - ec
      - echest
      - ender
  i:
    description: Admin command for giving items
    aliases:
      - item
  balance:
    description: Shows balance of player(s)
    aliases:
      - bal
      - money
  anvil:
    description: Opens an anvil
  pay:
    description: Pay money to another player
  paytoggle:
    description: Toggle pay requests
  repair:
    description: Repairs item in hand
    aliases:
      - fix
  hat:
    description: Puts item in hand on head
  tv:
    description: Time vote
    aliases:
      - timevote
  tpa:
    description: Teleport request
  tpaccept:
    description: Accept teleport request
  tpdeny:
    description: Deny teleport request
  tptoggle:
    description: Toggle teleport requests
  freeze:
    description: Freeze player
  unfreeze:
    description: Unfreeze player
  rtp:
    description: Random teleport
    aliases:
      - randomteleport
      - rt
  jail:
    description: Jail player
  unjail:
    description: Unjail player
  setjail:
    description: Set jail location
  netherlist:
    description: List of people in nether
  playerwarps:
    description: List of player warps
    aliases:
      - pw
      - playerwarp
      - pwarps
      - pwarp
  baltop:
    description: Show the top players with the highest balance



