name: Horizon
author: jogg15
version: ${version}
main: cz.goldzone.horizon.Main
api-version: '1.21'
softdepend: [Vault]

commands:
  horizon:
    description: Main command for Horizon plugin
  warp:
    description: Teleports to warp
  warps:
    description: List of warps
  setwarp:
    description: Set a warp
  delwarp:
    description: Delete a warp
  sethome:
    description: Set home location
  delhome:
    description: Delete home location
  home:
    description: Teleports to home
  homes:
    description: List of homes
  wb:
    description: Opens a crafting table
  enderchest:
    description: Opens an ender chest
    aliases:
      - ec
      - echest
      - ender
  i:
    description: Admin command for giving items
    aliases:
      - item
  balance:
    description: Shows balance of player(s)
    aliases:
      - bal
      - money
  anvil:
    description: Opens an anvil
  pay:
    description: Pay money to another player
  paytoggle:
    description: Toggle pay requests
  repair:
    description: Repairs item in hand
    aliases:
      - fix
  hat:
    description: Puts item in hand on head
  timevote:
    description: Time vote
    aliases:
      - tv
  timevote end:
    description: End time vote
    aliases:
      - tv end
  tpa:
    description: Teleport request
  tpaccept:
    description: Accept teleport request
  tpdeny:
    description: Deny teleport request
  tptoggle:
    description: Toggle teleport requests
  freeze:
    description: Freeze player
  unfreeze:
    description: Unfreeze player
  rtp:
    description: Random teleport to wilderness
    aliases:
      - randomteleport
      - rt
  jail:
    description: Jail player
  unjail:
    description: Unjail player
  setjail:
    description: Set jail location
  netherlist:
    description: List of people in nether
  playerwarps:
    description: List of player warps
    aliases:
      - pw
      - playerwarp
      - pwarps
      - pwarp
  baltop:
    description: Show the top players with the highest balance
  ratemessage:
    description: Make a thank you message if someone rates the player warp
    aliases:
        - ratemsg
  setspawnlocation:
    description: Set the spawn location for first-time players
  flyspeed:
    description: Set your fly speed
    aliases:
      - fs
  invsee:
    description: View and modify another player's inventory
  playerweather:
    description: Changes your personal weather
    aliases:
      - pweather
  feed:
    description: Feed yourself or another player
  heal:
    description: Heal yourself or another player
  playtime:
    description: Check your or another player's playtime
  god:
    description: Toggle god mode for yourself
  back:
    description: Teleport back to your last location



