name: Build
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: 21

      - uses: gradle/actions/setup-gradle@v4
        with:
          cache-overwrite-existing: true

      - name: Execute Gradle build
        run: ./gradlew shadowJar
        env:
          GOLDZONE_REPO_USERNAME: ${{ secrets.GOLDZONE_REPO_USERNAME }}
          GOLDZONE_REPO_PASSWORD: ${{ secrets.GOLDZONE_REPO_PASSWORD }}